In [5]:
import numpy as np

X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)  # X = (hours sleeping, hours studying)
y = np.array(([92], [86], [89]), dtype=float)  # y = score on test

# Scale units
X = X / np.amax(X, axis=0)  # Normalize input
y = y / 100  # Normalize output

class Neural_Network(object):
    def __init__(self):  # Fixed constructor name
        # Parameters
        self.inputSize = 2
        self.hiddenSize = 3
        self.outputSize = 1

        # Weights
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize)  # (2x3) weight matrix
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize)  # (3x1) weight matrix

    def forward(self, X):
        """Forward propagation"""
        self.z = np.dot(X, self.W1)  # Dot product of input and first weight layer
        self.z2 = self.sigmoid(self.z)  # Activation function
        self.z3 = np.dot(self.z2, self.W2)  # Dot product of hidden layer and second weight layer
        o = self.sigmoid(self.z3)  # Final activation function
        return o

    def sigmoid(self, s):
        """Sigmoid activation function"""
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
        """Derivative of sigmoid function"""
        return s * (1 - s)

    def backward(self, X, y, o):
        """Backward propagation"""
        self.o_error = y - o  # Output layer error
        self.o_delta = self.o_error * self.sigmoidPrime(o)  # Apply derivative of sigmoid

        self.z2_error = self.o_delta.dot(self.W2.T)  # Hidden layer error
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.z2)  # Apply derivative of sigmoid

        # Update weights
        self.W1 += X.T.dot(self.z2_delta)
        self.W2 += self.z2.T.dot(self.o_delta)

    def train(self, X, y):
        """Train the network"""
        o = self.forward(X)
        self.backward(X, y, o)

# Create Neural Network
NN = Neural_Network()

# Train the network
for i in range(1):  # Train 1,000 times
    print("\nInput: \n" + str(X))
    print("\nActual Output: \n" + str(y))
    
    predicted_output = NN.forward(X)
    print("\nPredicted Output: \n" + str(predicted_output))
    
    loss = np.mean(np.square(y - predicted_output))  # Mean squared loss
    print("\nLoss: \n" + str(loss))
    
    NN.train(X, y)



Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.35736972]
 [0.35066482]
 [0.35534979]]

Loss: 
0.28727533613990386

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.41097206]
 [0.40123904]
 [0.41146069]]

Loss: 
0.23285697706333833

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.4613006 ]
 [0.44946321]
 [0.46444221]]

Loss: 
0.18668167522349755

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.5071241 ]
 [0.49384463]
 [0.51279541]]

Loss: 
0.14893985629096165

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

